# -*- coding: utf-8 -*-
"""Spam_detector

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WQXeWLJ5nz_q3v91dvQRxubHKN8nhmuL
"""

import pandas as pd
import numpy as np
import re
import joblib
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.calibration import CalibratedClassifierCV  # FIX 1: Removed duplicate import

# ---------------------------------------------------
# 1) LOAD YOUR ENRON DATASET
# ---------------------------------------------------
df = pd.read_csv("Enron.csv")   # change filename if needed

# Ensure required columns
df["subject"] = df["subject"].fillna("")
df["body"] = df["body"].fillna("")
df["text"] = df["subject"] + " " + df["body"]
df["label"] = df["label"].astype(int)  # 0 = ham, 1 = spam

print("Dataset loaded. Label counts:")
print(df["label"].value_counts())

# ---------------------------------------------------
# 2) CLEAN TEXT
# ---------------------------------------------------
def clean_text(text):
    text = text.lower()
    text = re.sub(r"http\S+|www\S+", " url ", text)
    text = re.sub(r"[^a-z0-9\s]", " ", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text

df["clean"] = df["text"].apply(clean_text)

# ---------------------------------------------------
# 3) TRAIN-TEST SPLIT
# ---------------------------------------------------
X_train, X_test, y_train, y_test = train_test_split(
    df["clean"], df["label"], test_size=0.27, random_state=42
)

# ---------------------------------------------------
# 4) BUILD PIPELINE WITH LinearSVC
# ---------------------------------------------------
pipeline = Pipeline([
    ("tfidf", TfidfVectorizer(
        stop_words="english",
        max_df=0.95,
        min_df=3,
        ngram_range=(1, 2)
    )),

    ("clf", CalibratedClassifierCV(LinearSVC(), cv=5))
])

# ---------------------------------------------------
# 5) TRAIN
# ---------------------------------------------------
print("\nTraining model...")
pipeline.fit(X_train, y_train)

# ---------------------------------------------------
# 6) EVALUATE
# ---------------------------------------------------
preds = pipeline.predict(X_test)
print("\nAccuracy:", accuracy_score(y_test, preds))
print("\nClassification Report:\n", classification_report(y_test, preds))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, preds))

# ---------------------------------------------------
# 7) PREDICTION FUNCTION WITH THRESHOLD
# ---------------------------------------------------


THRESHOLD = 0.80  # You can adjust this

def predict_email(text):
    cleaned = clean_text(text)
    proba = pipeline.predict_proba([cleaned])[0]
    spam_prob = proba[1]
    ham_prob = proba[0]

    if spam_prob >= THRESHOLD:
        label = "SPAM"
        confidence = spam_prob
    else:
        label = "HAM"
        confidence = ham_prob

    return {
        "label": label,
        "spam_probability": float(spam_prob),
        "confidence_used": float(confidence)
    }

# ---------------------------------------------------
# 8) SAVE MODEL
# ---------------------------------------------------
joblib.dump(pipeline, "enron_svc_spam_model.joblib")
print("\nSaved model to enron_svc_spam_model.joblib")
# ---------------------------------------------------
# 9) USER INPUT LOOP
# ---------------------------------------------------
print("\nModel ready! Test manually:")
while True:
    user_in = input("\nType a message to test (or 'exit'): ").strip()
    if user_in.lower() == "exit":
        break
    result = predict_email(user_in)
    print(f"\nPrediction: {result['label']}")
    print(f"Spam Probability: {result['spam_probability']:.4f}")
    print(f"Confidence Used: {result['confidence_used']:.4f}")